### ISSUE TITLE
is your website down?

### ISSUE THREAD

**Issue by sctech-tr** [GabubuAvailable/GabubuAvailable#1]
I went to gabubu.xyz and saw this:
![resim](https://github.com/user-attachments/assets/b652615c-d376-4c6e-bd1e-f3db10b12409)
Is your website down?
or you don't use the domain anymore?
This is just to inform you.

**Comment by GabubuAvailable** [comment]
Heyo! I'm not even hosting it due to some reasons. But I plan to bring it to life someday!
